---
abstract: 'Client Libraries to Iron services IronCache, IronMQ and IronWorker.'
author:
  - 'Mikko Koivunalho <mikko.koivunalho@iki.fi>'
build_requires:
  Archive::Zip: 1.3
  File::Copy: 2.21
  File::Remove: 1.52
  IO::String: 1.08
  Log::Any::Test: 0.15
  Test::Exception: 0.31
  Test::More: 0
  YAML::Tiny: 1.51
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.131560'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Iron
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 1.26
  Carp::Assert: 0.2
  Carp::Assert::More: 1.12
  Data::UUID: 1.219
  English: 0
  Exception::Class: 1.37
  File::HomeDir: 1
  File::Slurp: 9999.19
  File::Spec: 0
  Hash::Util: 0
  JSON: 2.53
  Log::Any: 0.15
  Params::Validate: 1.08
  REST::Client: 88
  Scalar::Util: 0
  Try::Tiny: 0.18
  URI::Escape: 3.31
  perl: 5.006002
version: 0.06
